CREATE TABLE IF NOT EXISTS MPA_RATING (
	MPA_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME CHARACTER VARYING(20) NOT NULL,
	DESCRIPTION CHARACTER VARYING(100)
);

CREATE TABLE IF NOT EXISTS GENRE (
	GENRE_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME CHARACTER VARYING(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS FILM (
	FILM_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME CHARACTER VARYING(100) NOT NULL,
	DESCRIPTION CHARACTER VARYING(200) NOT NULL,
	RELEASE_DATE DATE NOT NULL,
	DURATION INTEGER NOT NULL,
	RATE INTEGER,
	MPA_ID INTEGER NOT NULL REFERENCES MPA_RATING (MPA_ID)
);

CREATE TABLE IF NOT EXISTS FILM_GENRE (
	FILM_ID INTEGER NOT NULL REFERENCES FILM (FILM_ID),
	GENRE_ID INTEGER NOT NULL REFERENCES GENRE (GENRE_ID)
);

CREATE TABLE IF NOT EXISTS CUSTOMER (
	CUSTOMER_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	LOGIN CHARACTER VARYING(30) NOT NULL,
	NAME CHARACTER VARYING(50) NOT NULL,
	EMAIL CHARACTER VARYING(254) NOT NULL,
	BIRTHDAY DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS CUSTOMER_FRIEND (
	USER_ID INTEGER NOT NULL REFERENCES CUSTOMER (CUSTOMER_ID),
	FRIEND_ID INTEGER NOT NULL REFERENCES CUSTOMER (CUSTOMER_ID),
	STATUS BOOLEAN NOT NULL,
	UNIQUE (USER_ID, FRIEND_ID)
);